### ISSUE TITLE
Icon Path in widget_ddtlabs_hm.html in hm_rtr

### ISSUE THREAD

**Issue by Starc86** [ddtlabs/smartvisu-widgets#2]
Widget hm_rtr 
Icon Path is Wrong in widget_ddtlabs_hm.html 
No Icon Path is defined.
Icons will not Show

Icon Pfad ist bei manchen eintragen nicht vorhanden und muss ergänzt werden mit 
icons/ws/<image>

**Comment by ddtlabs** [comment]
Are you using smartvisu 2.7 or 2.8pre?

**Comment by Starc86** [comment]
Im using 2.7 is it important ?

**Comment by ddtlabs** [comment]
Requirements:
    Fully functioning FHEM with configured HM rtr devices.
    SmartVISU 2.8+ (https://github.com/Martin-Gleiss/smartvisu)
