### ISSUE TITLE
Gad not editable in FHEM

### ISSUE THREAD

**Issue by NetRat88** [ddtlabs/smartvisu-widgets#3]
I copied the widget_hue.html in the folder /pages/mypage/ and copied the widget_hue.css content into my visu.css.
Than I added {% import "widget_hue.html" as hue %} in my romm_living.html in /pages/mypage at the top and used {{ hue.extcolordimmer('CouchBacklightDimmer','CouchBacklight Dimmer',16,20) }} for my device. After refreshing the smartvisu page and than the FHEM page I could find the gads but if I now click on one of these gads I am not able to edit and set the converters.
Any idea?

Best regards

**Comment by ddtlabs** [comment]
Use forum.fhem.de for support, please.
