### ISSUE TITLE
Cover URL ist not transferred from FHEM (SmartVisu 2.8)

### ISSUE THREAD

**Issue by bbg41crew** [ddtlabs/smartvisu-widgets#5]
Hi, 

thank you very much for this great Widget. The only issue is that in my Smartvisu 2.8 the transfer of the Covers into the Widget does not work. I can only see the empty.jpg. Accordingly, I assume that the basic algorithm works - to me it seems that the Url of the cover ist not transferred. When I directly enter the respective URL in the Firefox Developer Tools the Cover ist displayed. Unfortunately, I couldn't fix the issue myself and thus I ask for you help.

Thanks in advance!

**Comment by ddtlabs** [comment]
Sounds like a configuration error. I can not reproduce this behavior

**Comment by bbg41crew** [comment]
You are so right - it costed me a lot of time to figure out that I forgot to include the widget_ddtlabs_sonos.js in the visu.js in the pages/myflat-Folder. Symptoms are that the playlists, favourites and the covers are not displayed. I resolved it by entering the following code into the visu.js. Hope this will help others with the same issue.

```
// -----------------------------------------------------------------------------
// Function to include code from widget_xxx.js (by HCS)
// For details see: http://forum.fhem.de/index.php/topic,30909.msg276209.html#msg276209
// -----------------------------------------------------------------------------

var scriptFolder = (function() {
  var result = document.currentScript.getAttribute("src", 2);
  return result.substring(0, result.lastIndexOf("/") +1);
}());

function include(script) {
  script = scriptFolder + script;
  $.ajax({
    url: script,
    dataType: "script",
    async: false,
    error: function () {
      alert("Could not load '" + script + "'");
    }
  });
}

// -----------------------------------------------------------------------------
// Widgets to include...
// -----------------------------------------------------------------------------
include("widget_ddtlabs_sonos.js");
// -----------------------------------------------------------------------------
```
